# NGINX TCP load balancer for Kubernetes cluster
# 6443 -> Kubernetes API server
# 443  -> Ingress controller (HTTPS passthrough)

worker_processes auto;

events {
    worker_connections 4096;
}

stream {

    upstream k8s_api {
	least_conn;
	server <control-plane-1-ip>:6443 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 6443 reuseport so_keepalive=5m:30s:5;
        proxy_pass k8s_api;
        proxy_timeout 60s;
        proxy_connect_timeout 5s;
    }

    upstream k8s_ingress {
        least_conn;
        server <worker-1-ip>:443 max_fails=3 fail_timeout=30s;
        server <worker-2-ip>:443 max_fails=3 fail_timeout=30s;
        server <worker-3-ip>:443 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 443 reuseport so_keepalive=5m:30s:5;
        proxy_pass k8s_ingress;
        proxy_timeout 10m;
        proxy_connect_timeout 5s;
    }

}
