apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-qbittorrent-smb
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-qbittorrent-smb
  storageClassName: smb-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-qbittorrent
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-truenas
