apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gokapi
  namespace: gokapi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-truenas
