apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-smb
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-jellyfin-smb
  storageClassName: smb-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-truenas
